language: node_js
node_js:
  - 'node'
  - '6'
install: npm install
addons:
  code_climate:
    repo_token: c348bb60c0659ca8c1afe04ca7738e1681138e1ce0a30daaa5e7de11016888ad
notifications:
  email: false
  slack:
    rooms:
      secure: fy1OknwCZ8CfoqNpplKzQFu1zsiOLVYUcTbnqmSa5B+sM6itGOQPyiz/alAaFAcVM1pfvX2JQN2I7azuSc92x3c1zkQkRKPpVH0dFoJ7Ep9gxMQOX97qbKEeLCNHRA6oAG1QHlJysNTe7lCi9cJLy5vcMvgVnhuWjHB15/veMHjU0CLfgriZoELFTuV8+DbkHE0h2tdbXttPeSDb2F1wj/Fuki7oaJdaB0V1XRyS0iMK9bZunltGfYQs90aK9iHHM1Rlt4HertCxfa7U+B6pubfSPafsas9OMJ/EygWGMUt71H4yaZ6ev2a+2gk3HXGzBMTAl5CqmASu07uZNm6CZ82Ua1lD2Cv67CCnK2LX6/jOw3GmIXQJb0le0rL2GVe01e9XkH+jdq0Xv16YKlpWytFv/I5Tobg+VDV5CV84GigaBcoQ88E6PFSdM0btXXx1r+GguCKlLJ6bgdZ/+WS9Rx7E3T3TfL1eywVqryxF/1Ri3rNzbbIDqFveikchZ1kN9nzchj3AoPqV3y+9+h7jwgZMtRzmeM4ec3xXWAZTa5oPa8vQdtWv3UsdAtpAMDrXJKA/9G1XJoDPTDhq1TtLCdeoT9phYu9e19bAgjOoR2tdnjMvNidYdYIqbTFb295ahQS+QY8+uhj4Fzpco6Zuj5X0xlbpPkQX/juKKoaPpAU=
before_script:
  - npm install -g codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
